openapi: 3.0.1
info:
  description: This is the API that is used to upload symbols to Cloud Symbol Server
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Cloud Symbol Server Uplaod API
  version: 1.0.0
servers:
- url: /
security:
- emailAndPat: []
paths:
  /stores:
    get:
      operationId: getStores
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getStoresResponse'
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: Not authorized
      summary: Fetch a list of all stores
  /stores/{store}:
    delete:
      operationId: deleteStore
      parameters:
      - description: ID of store to delete
        explode: false
        in: path
        name: store
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Success
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: Store does not exist
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: Not authorized
      summary: Delete an existing store
    post:
      operationId: createStore
      parameters:
      - description: ID of store to create
        explode: false
        in: path
        name: store
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Success
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: Store already exists
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: Not authorized
      summary: Create a new store
  /stores/{storeId}/transactions:
    post:
      operationId: createTransaction
      parameters:
      - description: ID of the store containing the transactions
        explode: false
        in: path
        name: storeId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/uploadTransactionRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/uploadTransactionResponse'
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: Not authorized
      summary: Start a new upload transaction
  /stores/{storeId}/transactions/{transactionId}:
    get:
      operationId: getTransaction
      parameters:
      - description: ID of the transaction to fetch
        explode: false
        in: path
        name: transactionId
        required: true
        schema:
          type: string
        style: simple
      - description: ID of the store containing the transaction
        explode: false
        in: path
        name: storeId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getTransactionResponse'
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: Not authorized
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: No such store/transaction
      summary: Fetch a transaction
components:
  schemas:
    messageResponse:
      properties:
        message:
          example: Invalid API invocation
          type: string
      type: object
    getStoresResponse:
      items:
        example: example-store
        type: string
      type: array
    uploadTransactionRequest:
      properties:
        description:
          example: Example application
          type: string
        buildId:
          example: Build 432
          type: string
        files:
          items:
            $ref: '#/components/schemas/uploadFileRequest'
          type: array
      type: object
    uploadFileRequest:
      properties:
        fileName:
          example: Application.pdb
          type: string
        hash:
          example: 7F416863ABF34C3E894BAD1739BAA5571
          type: string
      type: object
    uploadTransactionResponse:
      example:
        files:
        - fileName: Application.pdb
          hash: 7F416863ABF34C3E894BAD1739BAA5571
          url: https://storage.googleapis.com/storage/v1/b/example-bucket/o/stores/default/Application.pdb/7F416863ABF34C3E894BAD1739BAA5571/Application.pdb?GoogleAcountID=123456&Sign=123012301230124012401240124012031021024012401240124012401240241
        - fileName: Application.pdb
          hash: 7F416863ABF34C3E894BAD1739BAA5571
          url: https://storage.googleapis.com/storage/v1/b/example-bucket/o/stores/default/Application.pdb/7F416863ABF34C3E894BAD1739BAA5571/Application.pdb?GoogleAcountID=123456&Sign=123012301230124012401240124012031021024012401240124012401240241
        id: s4elWg054qyrpHCsHqLq
      properties:
        id:
          example: s4elWg054qyrpHCsHqLq
          type: string
        files:
          items:
            $ref: '#/components/schemas/uploadFileResponse'
          type: array
      type: object
    uploadFileResponse:
      example:
        fileName: Application.pdb
        hash: 7F416863ABF34C3E894BAD1739BAA5571
        url: https://storage.googleapis.com/storage/v1/b/example-bucket/o/stores/default/Application.pdb/7F416863ABF34C3E894BAD1739BAA5571/Application.pdb?GoogleAcountID=123456&Sign=123012301230124012401240124012031021024012401240124012401240241
      properties:
        fileName:
          example: Application.pdb
          type: string
        hash:
          example: 7F416863ABF34C3E894BAD1739BAA5571
          type: string
        url:
          example: https://storage.googleapis.com/storage/v1/b/example-bucket/o/stores/default/Application.pdb/7F416863ABF34C3E894BAD1739BAA5571/Application.pdb?GoogleAcountID=123456&Sign=123012301230124012401240124012031021024012401240124012401240241
          type: string
      type: object
    getTransactionResponse:
      example:
        description: Example application
        files:
        - fileName: Application.pdb
          hash: 7F416863ABF34C3E894BAD1739BAA5571
        - fileName: Application.pdb
          hash: 7F416863ABF34C3E894BAD1739BAA5571
        buildId: Build 432
        timestamp: 2019-10-12T07:20:50.52Z
      properties:
        description:
          example: Example application
          type: string
        buildId:
          example: Build 432
          type: string
        timestamp:
          example: 2019-10-12T07:20:50.52Z
          type: string
        files:
          items:
            $ref: '#/components/schemas/getFileResponse'
          type: array
      type: object
    getFileResponse:
      example:
        fileName: Application.pdb
        hash: 7F416863ABF34C3E894BAD1739BAA5571
      properties:
        fileName:
          example: Application.pdb
          type: string
        hash:
          example: 7F416863ABF34C3E894BAD1739BAA5571
          type: string
      type: object
  securitySchemes:
    emailAndPat:
      scheme: basic
      type: http
