openapi: 3.0.1
info:
  description: This is the API that is used to manage stores and uploads in Cloud
    Symbol Server
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Cloud Symbol Server Admin API
  version: 1.0.0
servers:
- url: /
security:
- emailAndPat: []
paths:
  /stores:
    get:
      operationId: getStores
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getStoresResponse'
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: Not authorized
      summary: Fetch a list of all stores
  /stores/{storeId}:
    delete:
      operationId: deleteStore
      parameters:
      - description: ID of store to delete
        explode: false
        in: path
        name: storeId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: Not authorized
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: Store does not exist
      summary: Delete an existing store
    post:
      operationId: createStore
      parameters:
      - description: ID of store to create
        explode: false
        in: path
        name: storeId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: Not authorized
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: Store already exists
      summary: Create a new store
  /stores/{storeId}/uploads:
    get:
      operationId: getStoreUploadIds
      parameters:
      - description: ID of the store containing the uploads
        explode: false
        in: path
        name: storeId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getStoreUploadIdsResponse'
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: Not authorized
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: No such store
      summary: Fetch a list of all uploads in store
    post:
      operationId: createStoreUpload
      parameters:
      - description: ID of the store containing the upload
        explode: false
        in: path
        name: storeId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createStoreUploadRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createStoreUploadResponse'
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: Not authorized
      summary: Start a new upload
  /stores/{storeId}/uploads/{uploadId}:
    get:
      operationId: getStoreUpload
      parameters:
      - description: ID of the upload to fetch
        explode: false
        in: path
        name: uploadId
        required: true
        schema:
          type: string
        style: simple
      - description: ID of the store containing the upload
        explode: false
        in: path
        name: storeId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getStoreUploadResponse'
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: Not authorized
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: No such store/upload
      summary: Fetch an upload
components:
  responses:
    "401":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/messageResponse'
      description: Not authorized
  schemas:
    messageResponse:
      properties:
        message:
          example: Invalid API invocation
          type: string
      type: object
    getStoresResponse:
      items:
        example: example-store
        type: string
      type: array
    createStoreUploadRequest:
      properties:
        description:
          example: Example application
          type: string
        buildId:
          example: Build 432
          type: string
        files:
          items:
            $ref: '#/components/schemas/uploadFileRequest'
          type: array
      type: object
    uploadFileRequest:
      properties:
        fileName:
          example: Application.pdb
          type: string
        hash:
          example: 7F416863ABF34C3E894BAD1739BAA5571
          type: string
      type: object
    getStoreUploadIdsResponse:
      items:
        example: '["1","2","3"]'
        type: string
      type: array
    createStoreUploadResponse:
      example:
        files:
        - fileName: Application.pdb
          hash: 7F416863ABF34C3E894BAD1739BAA5571
          url: https://storage.googleapis.com/storage/v1/b/example-bucket/o/stores/default/Application.pdb/7F416863ABF34C3E894BAD1739BAA5571/Application.pdb?GoogleAcountID=123456&Sign=123012301230124012401240124012031021024012401240124012401240241
        - fileName: Application.pdb
          hash: 7F416863ABF34C3E894BAD1739BAA5571
          url: https://storage.googleapis.com/storage/v1/b/example-bucket/o/stores/default/Application.pdb/7F416863ABF34C3E894BAD1739BAA5571/Application.pdb?GoogleAcountID=123456&Sign=123012301230124012401240124012031021024012401240124012401240241
        id: s4elWg054qyrpHCsHqLq
      properties:
        id:
          example: s4elWg054qyrpHCsHqLq
          type: string
        files:
          items:
            $ref: '#/components/schemas/uploadFileResponse'
          type: array
      type: object
    uploadFileResponse:
      example:
        fileName: Application.pdb
        hash: 7F416863ABF34C3E894BAD1739BAA5571
        url: https://storage.googleapis.com/storage/v1/b/example-bucket/o/stores/default/Application.pdb/7F416863ABF34C3E894BAD1739BAA5571/Application.pdb?GoogleAcountID=123456&Sign=123012301230124012401240124012031021024012401240124012401240241
      properties:
        fileName:
          example: Application.pdb
          type: string
        hash:
          example: 7F416863ABF34C3E894BAD1739BAA5571
          type: string
        url:
          example: https://storage.googleapis.com/storage/v1/b/example-bucket/o/stores/default/Application.pdb/7F416863ABF34C3E894BAD1739BAA5571/Application.pdb?GoogleAcountID=123456&Sign=123012301230124012401240124012031021024012401240124012401240241
          type: string
      type: object
    getStoreUploadResponse:
      example:
        description: Example application
        files:
        - fileName: Application.pdb
          hash: 7F416863ABF34C3E894BAD1739BAA5571
        - fileName: Application.pdb
          hash: 7F416863ABF34C3E894BAD1739BAA5571
        buildId: Build 432
        timestamp: 2019-10-12T07:20:50.52Z
      properties:
        description:
          example: Example application
          type: string
        buildId:
          example: Build 432
          type: string
        timestamp:
          example: 2019-10-12T07:20:50.52Z
          type: string
        files:
          items:
            $ref: '#/components/schemas/getFileResponse'
          type: array
      type: object
    getFileResponse:
      example:
        fileName: Application.pdb
        hash: 7F416863ABF34C3E894BAD1739BAA5571
      properties:
        fileName:
          example: Application.pdb
          type: string
        hash:
          example: 7F416863ABF34C3E894BAD1739BAA5571
          type: string
      type: object
  securitySchemes:
    emailAndPat:
      scheme: basic
      type: http
