openapi: 3.0.1
info:
  description: This is the API that is used to manage stores and uploads in Cloud
    Symbol Server
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Cloud Symbol Server Admin API
  version: 1.0.0
servers:
- url: /
security:
- emailAndPat: []
paths:
  /stores:
    get:
      operationId: getStores
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getStoresResponse'
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: Not authorized
      summary: Fetch a list of all stores
  /stores/{storeId}:
    delete:
      operationId: deleteStore
      parameters:
      - description: ID of store to delete
        explode: false
        in: path
        name: storeId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: Not authorized
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: Store does not exist
      summary: Delete an existing store
    post:
      operationId: createStore
      parameters:
      - description: ID of store to create
        explode: false
        in: path
        name: storeId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: Not authorized
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: Store already exists
      summary: Create a new store
  /stores/{storeId}/uploads:
    get:
      operationId: getStoreUploadIds
      parameters:
      - description: ID of the store containing the uploads
        explode: false
        in: path
        name: storeId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getStoreUploadIdsResponse'
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: Not authorized
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: No such store
      summary: Fetch a list of all uploads in store
    post:
      operationId: createStoreUpload
      parameters:
      - description: ID of the store containing the upload
        explode: false
        in: path
        name: storeId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createStoreUploadRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createStoreUploadResponse'
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: Not authorized
      summary: Start a new upload
  /stores/{storeId}/uploads/{uploadId}:
    get:
      operationId: getStoreUpload
      parameters:
      - description: ID of the upload to fetch
        explode: false
        in: path
        name: uploadId
        required: true
        schema:
          type: string
        style: simple
      - description: ID of the store containing the upload
        explode: false
        in: path
        name: storeId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getStoreUploadResponse'
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: Not authorized
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: No such store/upload
      summary: Fetch an upload
  /stores/{storeId}/uploads/{uploadId}/completed:
    post:
      operationId: markStoreUploadCompleted
      parameters:
      - description: ID of the upload to fetch
        explode: false
        in: path
        name: uploadId
        required: true
        schema:
          type: string
        style: simple
      - description: ID of the store containing the upload
        explode: false
        in: path
        name: storeId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: Not authorized
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: No such store/upload
      summary: Mark an upload as completed
  /stores/{storeId}/uploads/{uploadId}/aborted:
    post:
      operationId: markStoreUploadAborted
      parameters:
      - description: ID of the upload to mark as aborted
        explode: false
        in: path
        name: uploadId
        required: true
        schema:
          type: string
        style: simple
      - description: ID of the store containing the upload
        explode: false
        in: path
        name: storeId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: Not authorized
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: No such store/upload
      summary: Mark an upload as aborted
  /stores/{storeId}/uploads/{uploadId}/files/{fileId}/uploaded:
    post:
      operationId: markStoreUploadFileUploaded
      parameters:
      - description: ID of the upload to fetch
        explode: false
        in: path
        name: uploadId
        required: true
        schema:
          type: string
        style: simple
      - description: ID of the store containing the upload
        explode: false
        in: path
        name: storeId
        required: true
        schema:
          type: string
        style: simple
      - description: Index of the file within the upload that should be marked as
          uploaded
        explode: false
        in: path
        name: fileId
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: Not authorized
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'
          description: No such store/upload/item
      summary: Mark a file within an upload as uploaded
components:
  responses:
    "401":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/messageResponse'
      description: Not authorized
  schemas:
    messageResponse:
      properties:
        message:
          example: Invalid API invocation
          type: string
      type: object
    getStoresResponse:
      items:
        example: example-store
        type: string
      type: array
    createStoreUploadRequest:
      properties:
        useProgressApi:
          description: When present and set to true, the client will provide progress
            updates; Legacy clients will create an upload, then upload the required
            files to GCS, without progress/completion callbacks
          example: true
          type: boolean
        description:
          example: Example application
          type: string
        buildId:
          example: Build 432
          type: string
        files:
          items:
            $ref: '#/components/schemas/uploadFileRequest'
          type: array
      type: object
    uploadFileRequest:
      properties:
        fileName:
          example: Application.pdb
          type: string
        hash:
          example: 7F416863ABF34C3E894BAD1739BAA5571
          type: string
      type: object
    getStoreUploadIdsResponse:
      items:
        example: '["1","2","3"]'
        type: string
      type: array
    createStoreUploadResponse:
      example:
        files:
        - fileName: Application.pdb
          hash: 7F416863ABF34C3E894BAD1739BAA5571
          url: https://storage.googleapis.com/storage/v1/b/example-bucket/o/stores/default/Application.pdb/7F416863ABF34C3E894BAD1739BAA5571/Application.pdb?GoogleAcountID=123456&Sign=123012301230124012401240124012031021024012401240124012401240241
        - fileName: Application.pdb
          hash: 7F416863ABF34C3E894BAD1739BAA5571
          url: https://storage.googleapis.com/storage/v1/b/example-bucket/o/stores/default/Application.pdb/7F416863ABF34C3E894BAD1739BAA5571/Application.pdb?GoogleAcountID=123456&Sign=123012301230124012401240124012031021024012401240124012401240241
        id: s4elWg054qyrpHCsHqLq
      properties:
        id:
          example: s4elWg054qyrpHCsHqLq
          type: string
        files:
          items:
            $ref: '#/components/schemas/uploadFileResponse'
          type: array
      type: object
    uploadFileResponse:
      example:
        fileName: Application.pdb
        hash: 7F416863ABF34C3E894BAD1739BAA5571
        url: https://storage.googleapis.com/storage/v1/b/example-bucket/o/stores/default/Application.pdb/7F416863ABF34C3E894BAD1739BAA5571/Application.pdb?GoogleAcountID=123456&Sign=123012301230124012401240124012031021024012401240124012401240241
      properties:
        fileName:
          example: Application.pdb
          type: string
        hash:
          example: 7F416863ABF34C3E894BAD1739BAA5571
          type: string
        url:
          description: Short-lived signed URL where the client should upload the file
            to, or blank if the file already exists in the storage backend
          example: https://storage.googleapis.com/storage/v1/b/example-bucket/o/stores/default/Application.pdb/7F416863ABF34C3E894BAD1739BAA5571/Application.pdb?GoogleAcountID=123456&Sign=123012301230124012401240124012031021024012401240124012401240241
          type: string
      type: object
    getStoreUploadResponse:
      example:
        description: Example application
        files:
        - fileName: Application.pdb
          hash: 7F416863ABF34C3E894BAD1739BAA5571
          status: uploaded
        - fileName: Application.pdb
          hash: 7F416863ABF34C3E894BAD1739BAA5571
          status: uploaded
        buildId: Build 432
        timestamp: 2019-10-12T07:20:50.52Z
        status: completed
      properties:
        description:
          example: Example application
          type: string
        buildId:
          example: Build 432
          type: string
        timestamp:
          example: 2019-10-12T07:20:50.52Z
          type: string
        files:
          items:
            $ref: '#/components/schemas/getFileResponse'
          type: array
        status:
          enum:
          - unknown
          - in_progress
          - completed
          - aborted
          example: completed
          type: string
      type: object
    getFileResponse:
      example:
        fileName: Application.pdb
        hash: 7F416863ABF34C3E894BAD1739BAA5571
        status: uploaded
      properties:
        fileName:
          example: Application.pdb
          type: string
        hash:
          example: 7F416863ABF34C3E894BAD1739BAA5571
          type: string
        status:
          enum:
          - unknown
          - already_present
          - pending
          - uploaded
          - aborted
          example: uploaded
          type: string
      type: object
  securitySchemes:
    emailAndPat:
      scheme: basic
      type: http
