openapi: 3.0.1

info:
  title: Cloud Symbol Server Admin API
  description: 'This is the API that is used to manage stores and uploads in Cloud Symbol Server'
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0

paths:
  /stores:
    get:
      summary: Fetch a list of all stores
      operationId: getStores

      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getStoresResponse'

        401:
          $ref: '#/components/responses/401'

  /stores/{storeId}:
    post:
      summary: Create a new store
      operationId: createStore
      parameters:
        - in: path
          name: storeId
          schema:
            type: string
          required: true
          description: ID of store to create

      responses:
        200:
          description: Success

        401:
          $ref: '#/components/responses/401'

        409:
          description: Store already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'

    delete:
      summary: Delete an existing store
      operationId: deleteStore
      parameters:
        - in: path
          name: storeId
          schema:
            type: string
          required: true
          description: ID of store to delete

      responses:
        200:
          description: Success

        401:
          $ref: '#/components/responses/401'

        404:
          description: Store does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'

  /stores/{storeId}/uploads:
    get:
      summary: Fetch a list of all uploads in store
      operationId: getStoreUploadIds
      parameters:
        - in: path
          name: storeId
          schema:
            type: string
          required: true
          description: ID of the store containing the uploads

      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getStoreUploadIdsResponse'

        401:
          $ref: '#/components/responses/401'

        404:
          description: No such store
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'

    post:
      summary: Start a new upload
      operationId: createStoreUpload
      parameters:
        - in: path
          name: storeId
          schema:
            type: string
          required: true
          description: ID of the store containing the upload
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createStoreUploadRequest'
      
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createStoreUploadResponse'

        401:
          $ref: '#/components/responses/401'

  /stores/{storeId}/uploads/{uploadId}:
    get:
      summary: Fetch an upload
      operationId: getStoreUpload
      parameters:
        - in: path
          name: uploadId
          schema:
            type: string
          required: true
          description: ID of the upload to fetch
        - in: path
          name: storeId
          schema:
            type: string
          required: true
          description: ID of the store containing the upload
      
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getStoreUploadResponse'

        401:
          $ref: '#/components/responses/401'

        404:
          description: No such store/upload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'

  /stores/{storeId}/uploads/{uploadId}/completed:
    post:
      summary: Mark an upload as completed
      operationId: markStoreUploadCompleted
      parameters:
        - in: path
          name: uploadId
          schema:
            type: string
          required: true
          description: ID of the upload to fetch
        - in: path
          name: storeId
          schema:
            type: string
          required: true
          description: ID of the store containing the upload

      responses:
        200:
          description: Success

        401:
          $ref: '#/components/responses/401'

        404:
          description: No such store/upload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'

  /stores/{storeId}/uploads/{uploadId}/aborted:
    post:
      summary: Mark an upload as aborted
      operationId: markStoreUploadAborted
      parameters:
        - in: path
          name: uploadId
          schema:
            type: string
          required: true
          description: ID of the upload to mark as aborted
        - in: path
          name: storeId
          schema:
            type: string
          required: true
          description: ID of the store containing the upload

      responses:
        200:
          description: Success

        401:
          $ref: '#/components/responses/401'

        404:
          description: No such store/upload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'

  /stores/{storeId}/uploads/{uploadId}/files/{fileId}/uploaded:
    post:
      summary: Mark a file within an upload as uploaded
      operationId: markStoreUploadFileUploaded
      parameters:
        - in: path
          name: uploadId
          schema:
            type: string
          required: true
          description: ID of the upload to fetch
        - in: path
          name: storeId
          schema:
            type: string
          required: true
          description: ID of the store containing the upload
        - in: path
          name: fileId
          schema:
            type: integer
          required: true
          description: Index of the file within the upload that should be marked as uploaded

      responses:
        200:
          description: Success

        401:
          $ref: '#/components/responses/401'

        404:
          description: No such store/upload/item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'

components:

  responses:
    401:
      description: Not authorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/messageResponse'

  schemas:

    messageResponse:
      type: object
      properties:
        message:
          type: string
          example: Invalid API invocation

    getStoresResponse:
      type: array
      items:
        type: string
        example: example-store

    createStoreUploadRequest:
      type: object
      properties:
        useProgressApi:
          type: boolean
          example: true
          description: When present and set to true, the client will provide progress updates;
            Legacy clients will create an upload, then upload the required files to GCS, without
            progress/completion callbacks
        description:
          type: string
          example: Example application
        buildId:
          type: string
          example: Build 432
        files:
          type: array
          items:
            $ref: '#/components/schemas/uploadFileRequest'

    uploadFileRequest:
      type: object
      properties:
        fileName:
          type: string
          example: Application.pdb
        hash:
          type: string
          example: 7F416863ABF34C3E894BAD1739BAA5571

    getStoreUploadIdsResponse:
      type: array
      items:
        type: string
        example: 
          - "1"
          - "2"
          - "3"

    createStoreUploadResponse:
      type: object
      properties:
        id:
          type: string
          example: s4elWg054qyrpHCsHqLq
        files:
          type: array
          items:
            $ref: '#/components/schemas/uploadFileResponse'

    uploadFileResponse:
      type: object
      properties:
        fileName:
          type: string
          example: Application.pdb
        hash:
          type: string
          example: 7F416863ABF34C3E894BAD1739BAA5571
        url:
          type: string
          example: https://storage.googleapis.com/storage/v1/b/example-bucket/o/stores/default/Application.pdb/7F416863ABF34C3E894BAD1739BAA5571/Application.pdb?GoogleAcountID=123456&Sign=123012301230124012401240124012031021024012401240124012401240241
          description: Short-lived signed URL where the client should upload the file to, or blank if the file already exists in the storage backend

    getStoreUploadResponse:
      type: object
      properties:
        description:
          type: string
          example: Example application
        buildId:
          type: string
          example: Build 432
        timestamp:
          type: string
          example: '2019-10-12T07:20:50.52Z'
        files:
          type: array
          items:
            $ref: '#/components/schemas/getFileResponse'
        status:
          type: string
          example: completed
          enum:
            - unknown
            - in_progress
            - completed
            - aborted

    getFileResponse:
      type: object
      properties:
        fileName:
          type: string
          example: Application.pdb
        hash:
          type: string
          example: 7F416863ABF34C3E894BAD1739BAA5571
        status:
          type: string
          example: uploaded
          enum:
            - unknown
            - already_present
            - pending
            - uploaded
            - aborted

  securitySchemes:
    emailAndPat:
      type: http
      scheme: basic

security:
  - emailAndPat: []
