openapi: 3.0.1

info:
  title: Cloud Symbol Server Admin API
  description: 'This is the API that is used to manage stores and uploads in Cloud Symbol Server'
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0

paths:
  /stores:
    get:
      summary: Fetch a list of all stores
      operationId: getStores

      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getStoresResponse'

        401:
          description: Not authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'

  /stores/{storeId}:
    post:
      summary: Create a new store
      operationId: createStore
      parameters:
        - in: path
          name: storeId
          schema:
            type: string
          required: true
          description: ID of store to create

      responses:
        200:
          description: Success

        409:
          description: Store already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'

        401:
          description: Not authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'

    delete:
      summary: Delete an existing store
      operationId: deleteStore
      parameters:
        - in: path
          name: storeId
          schema:
            type: string
          required: true
          description: ID of store to delete

      responses:
        200:
          description: Success

        404:
          description: Store does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'

        401:
          description: Not authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'

  /stores/{storeId}/uploads:
    get:
      summary: Fetch a list of all uploads in store
      operationId: getStoreUploads
      parameters:
        - in: path
          name: storeId
          schema:
            type: string
          required: true
          description: ID of the store containing the uploads

      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getStoreUploadsResponse'

        401:
          description: Not authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'

        404:
          description: No such store
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'

    post:
      summary: Start a new upload
      operationId: createStoreUpload
      parameters:
        - in: path
          name: storeId
          schema:
            type: string
          required: true
          description: ID of the store containing the upload
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createStoreUploadRequest'
      
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createStoreUploadResponse'

        401:
          description: Not authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'

  /stores/{storeId}/uploads/{uploadId}:
    get:
      summary: Fetch an upload
      operationId: getStoreUpload
      parameters:
        - in: path
          name: uploadId
          schema:
            type: string
          required: true
          description: ID of the upload to fetch
        - in: path
          name: storeId
          schema:
            type: string
          required: true
          description: ID of the store containing the upload
      
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getStoreUploadResponse'

        401:
          description: Not authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'

        404:
          description: No such store/upload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/messageResponse'

components:
  schemas:

    messageResponse:
      type: object
      properties:
        message:
          type: string
          example: Invalid API invocation

    getStoresResponse:
      type: array
      items:
        type: string
        example: example-store

    createStoreUploadRequest:
      type: object
      properties:
        description:
          type: string
          example: Example application
        buildId:
          type: string
          example: Build 432
        files:
          type: array
          items:
            $ref: '#/components/schemas/uploadFileRequest'

    uploadFileRequest:
      type: object
      properties:
        fileName:
          type: string
          example: Application.pdb
        hash:
          type: string
          example: 7F416863ABF34C3E894BAD1739BAA5571

    getStoreUploadsResponse:
      type: array
      items:
        type: string
        example: 
          - "1"
          - "2"
          - "3"

    createStoreUploadResponse:
      type: object
      properties:
        id:
          type: string
          example: s4elWg054qyrpHCsHqLq
        files:
          type: array
          items:
            $ref: '#/components/schemas/uploadFileResponse'

    uploadFileResponse:
      type: object
      properties:
        fileName:
          type: string
          example: Application.pdb
        hash:
          type: string
          example: 7F416863ABF34C3E894BAD1739BAA5571
        url:
          type: string
          example: https://storage.googleapis.com/storage/v1/b/example-bucket/o/stores/default/Application.pdb/7F416863ABF34C3E894BAD1739BAA5571/Application.pdb?GoogleAcountID=123456&Sign=123012301230124012401240124012031021024012401240124012401240241

    getStoreUploadResponse:
      type: object
      properties:
        description:
          type: string
          example: Example application
        buildId:
          type: string
          example: Build 432
        timestamp:
          type: string
          example: '2019-10-12T07:20:50.52Z'
        files:
          type: array
          items:
            $ref: '#/components/schemas/getFileResponse'

    getFileResponse:
      type: object
      properties:
        fileName:
          type: string
          example: Application.pdb
        hash:
          type: string
          example: 7F416863ABF34C3E894BAD1739BAA5571

  securitySchemes:
    emailAndPat:
      type: http
      scheme: basic

security:
  - emailAndPat: []
